spring:
  application:
    name: customer-service
  data:
    mongodb:
      username: ahnis
      password: ahnis
      host: 192.168.29.60
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
