spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
#  datasource:
#    url: jdbc:postgresql://192.168.29.60:5432/order
#    username: ahnis
#    password: ahnis
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  application:
#    name: order-service
#server:
#  port: 8070
#
#application:
#  config:
#    #    for now not good practice
#    customer-url: http://localhost:8090/api/v1/customers
#    product-url: http://localhost:8050/api/v1/products
#    payment-url: http://localhost:8060/api/v1/products