spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    #    this name is very important
    name: discovery-service
eureka:
  instance:
    hostname: localhost
  client:
    #    VIMP DISCOVERY SERVICE SHOULD NOT REGISTER WITH ITSELF
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/
server:
  port: 8761